name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository onto the runner
        uses: actions/checkout@v2
        
      # Using the setup-node action is the recommended way of using Node.js with GitHub Actions 
      # because it ensures consistent behavior across different runners and different versions of Node.js.
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn build

      - name: Deploy application on Fireabse hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_ACTIONS_4AD2B }}"
          projectId: github-actions-4ad2b
          channelId: live
